### ISSUE TITLE
Non-UTF-8 characters in type_info.hpp

### ISSUE THREAD

**Issue by boris-kolpackov** [Ultramarine-Holdings-LLC/build2-uvw#1]
See upstream bug report: https://github.com/skypjack/uvw/issues/259

It would be good to patch this on our side until upstream acts since we are switching to `/utf-8` by default in `0.15.0`.

**Comment by boris-kolpackov** [comment]
Not sure if the " Add MSVC utf-8 flag" commit was meant to fix this. If so, that's not the fix. The fix is to get rid of the invalid characters in `type_info.hpp`. Please see the upstream fix for details.

**Comment by karen-arutyunov** [comment]
Fixed in 2.10.0+2.
